name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.2, v1.0.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Verify version matches manifest.json
        run: |
          MANIFEST_VERSION=$(jq -r '.version' manifest.json)
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [ "$MANIFEST_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: manifest.json version ($MANIFEST_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version check passed: $MANIFEST_VERSION"
      
      - name: Build extension
        run: |
          chmod +x build.sh
          ./build.sh
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: LockedIn v${{ steps.get_version.outputs.VERSION }}
          body_path: RELEASE_NOTES.md
          files: |
            lockedin-${{ steps.get_version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
